config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  devise_for :users
  post '/reactions',     to: 'reactions#user_reaction',      as: 'user_reaction'
  get '/my_reactions', to: 'reactions#post_with_reactions', as:'my_reactions'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments

    has_many :reactions
    has_many :users, through: :reactions
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :kind, acceptance: {
    accept: %w[like dislike boring neutral uninterested interested]
  }

  def self.kinds
    %w[like dislike boring uninterested interested]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
  has_many :posts
  has_many :comments
  has_many :reactions
  has_many :posts, through: :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
  
  
  protected
  
  def after_sign_in_path_for(resourse)
    posts_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :age])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :age])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :agregar_a_post, only: %i[ show new edit create update]
  before_action :authenticate_user!, except: %i[ index show new edit create ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user if user_signed_in?

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end

    def agregar_a_post
      @posts = Post.all.order(title: :asc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :redirect_si_user_no_coincide_con_creador_del_post, only: %i[ edit update destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def redirect_si_user_no_coincide_con_creador_del_post
      if current_user.id != @post.user_id
        redirect_to posts_path, notice: "No puedes hacer eso pillin!"
      end
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!

  def user_reaction
     @user = current_user
     @post = Post.find(params[:post_id])
     reaction = Reaction.find_by(user_id: @user.id, post_id: @post.id)
     if reaction
        return flash.now[:alert] = 'Reaccionaste a esta publicación'
     else
      @new_reaction = Reaction.new(user_id: @user.id, post_id: @post.id, kind: params[:kind])
      respond_to do |format|
        if @new_reaction.save!
          format.html { redirect_to post_path(@post), notice: "#{current_user.email} Le ha dado #{@new_reaction.kind}
              a esta publicación" }
        else
          format.html { redirect_to post_path(@post), status: :unprocessable_entity }
        end
      end
    end
  end

  def post_with_reactions
    @reactions = current_user.reactions
    post_ids = @reactions.map(&:post_id)
    @posts = Post.where(id: post_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment]) do |f| %>
  <div>
    <%= f.label :post_id, style: "display: block" %>
    <%= f.collection_select :post_id, @posts, :id, :title, { include_blank: "Elige un post..." } %>
  </div>
  <div class="mb-3">
    <%= f.label :content, "Comentario", class: "form-label" %>
    <%= f.text_area :content, class: "form-control", rows: 3 %>
  </div>

  <div class="d-grid">
    <%= f.submit "Enviar comentario", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1>Editar Comentario</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<h1>Comments</h1>

<div class="row">
  <% @comments.each do |comment| %>
  <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">
          <% if comment.user.present? %>
            <%= comment.user.name %>
          <% else %>
            Anónimo
          <% end %>
        </h5>
        <p class="card-text"><%= truncate(comment.content, length: 100) %></p> 
        <%= link_to "Ver este post", comment_path(comment), class: "btn btn-primary btn-sm" %>
      </div>
  </div>
  <% end %>
</div>

<%= link_to "Nuevo Comentario", new_comment_path %>

app/views/comments/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">Nuevo Comentario</h1>

  <%= render "form", comment: @comment %>

  <br>

  <div>
    <%= link_to "Back to comments", comments_path %>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="container text-center my-5">
  <div class="card shadow">
    <div class="card-body">
      <h1 class="display-4 text-info">Bienvenidos a <strong>Crazy4Cats</strong> 🐱</h1>
      <p class="lead text-secondary">
        Un lugar para los amantes de los gatos donde puedes compartir historias, comentar y reaccionar. 
      </p>
      <hr class="my-4">
      <p class="text-dark-emphasis fs-5">
        <strong>¿Listo para compartir?</strong> <br> ¡Inicia sesión! o ¡Comenta de forma anónima! 
      </p>
      <p class="text-info fs-5 mb-4">
        <strong>¿Te gustó algo?</strong> <br> ¡Reacciona a las publicaciones y comparte tu amor por los gatos!
      </p>
      <a href="<%= user_signed_in? ? new_post_path : new_user_session_path %>" class="btn btn-primary btn-lg px-5">
        <%= user_signed_in? ? "Crear Publicación" : "Inicia Sesión para Publicar" %>
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crazy4cats" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <% if flash[:notice] %>
       <p class="alert"><%= flash[:notice] %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1 class="text-center my-5">Publicaciones</h1>

<div class="mb-5 d-flex justify-content-end">
  <% if user_signed_in? %>
    <%= link_to "Nueva publicación", new_post_path, class:"btn btn-primary" %>
  <% end %>
</div>


<div class="row">
  <% @posts.each do |post| %>
    <div class="card col-md-4 mb-4">
     <div class="card-body">
        <h5 class="card-title text-center"><%= post.title %></h5>
        <br>
        <p class="card-text"><%= truncate(post.content, length: 100) %></p>
      </div>
      <div class="card-footer text-center">
          <%= link_to "Ver este post", post_path(post), class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  <% end %>
</div>

<div>
  <% if user_signed_in? %>
    <%= link_to "Nueva publicación", new_post_path, class:"btn btn-primary" %>
  <% end %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "Nuevo Post" %>

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card shadow">
        <div class="card-body">
          <h1 class="text-center mb-4">Nueva Publicación</h1>

          <%= render "form", post: @post %>

          <div class="text-center mt-4">
            <%= link_to "Volver a Posts", posts_path, class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container my-5">
  <p class="text-success text-center"><%= notice %></p>

  <h1 class="mb-4 text-center display-4"><%= @post.title %></h1>

  <div class="card mb-4 shadow-sm">
    <div class="card-body">
      <p class="fs-5"><%= @post.content %></p>
    </div>
    <div class="d-flex justify-content-between mb-4">
      <div>
        <%= render 'reactions/options' %>
      </div>
      <div>
        <%= render 'reactions/counters' %>
      </div>
    </div>
  </div>


  <div class="d-flex justify-content-center m-4">
      <%= link_to "Comentar", new_comment_path(@comment), class: "btn btn-primary mx-4" %>
      <%= link_to "Volver a Posts", posts_path, class: "btn btn-secondary mx-4" %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to "Editar", edit_post_path(@post), class: "btn btn-warning mx-4" %>
        <%= button_to "Eliminar Post", @post, method: :delete, data: { confirm: "¿Estás seguro de que deseas eliminar este post?" }, class: "btn btn-danger mx-4" %>
      <% end %>
  </div>

  
  <h4 class="mb-3 text-center">Comentarios</h4>
  <div class="card">
    <div class="card-body">
      <% if @comments.any? %>
        <% @comments.each do |comment| %>
          <div class="border-bottom pb-2 mb-3">
            <div class="d-flex align-items-center">
            <% if comment.user.present? %>
              <h5 class="mb-0"><%= comment.user.name %></h5>
            <% else %>
              <h5 class="mb-0">Anónimo</h5>
            <% end %>
            </div>
            <p class="mt-2"><%= comment.content %></p>
            <%= link_to "Ver este Comentario", comment_path(comment), class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reactions/_counters.html.erb
<div class="container">
  <ul>
    <% Reaction.kinds.each do |kind| %>
      <li> <%= @post.reactions.where(kind: kind).count %> - <%= kind %> </li>
    <% end %>
  </ul>
</div>

app/views/reactions/_options.html.erb
<div class="container">
  <ul>
    <% Reaction.kinds.each do |kind| %>
      <li><%= button_to "#{kind}", user_reaction_path(post_id: @post.id, kind: kind), method: :post %></li>
    <% end %>
  </ul>
</div>

app/views/reactions/post_with_reactions.html.erb
<div class="container my-5">
  <h1 class="text-center mb-4">Reacciones</h1>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6 col-lg-6 mb-3">
        <div class="card shadow-sm h-100">
          <div class="card-body">
            <!-- Título del post -->
            <h5 class="card-title"><%= post.title %></h5>

            <!-- Tipo de reacción -->
            <% if post.reactions.find_by(user_id: current_user.id) %>
               <p class="card-text">
                  Tu reacción: <strong><%= post.reactions.find_by(user_id: current_user.id).kind.capitalize %></strong>
                </p>
            <% else %>
              <p class="card-text text-muted">No has reaccionado aún.</p>
            <% end %>

            <!-- Botón de detalles -->
            <div class="d-grid">
              <%= link_to "Detalles del Post", post_path(post), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "Crazy4cats", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="nav-item">
         <%= link_to "Posts", posts_path, class:"nav-link active", ariaCurrent:"page" %>
      </div>   
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <% if user_signed_in? %>
                    Hola <%= current_user.email %>
                <% else %>
                    Incia Sesión o Regístrate
                <% end %>
          </a>
          <ul class="dropdown-menu">
                <% if user_signed_in? %>
                    <li><%= link_to "Mi Cuenta", edit_user_registration_path, class:"dropdown-item" %></li>
                    <li><%= link_to 'Tus reacciones', my_reactions_path, class:"dropdown-item" %></li>
                    <li><%= button_to 'Cerrar Sesión', destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Iniciar Sesión', new_user_session_path, class:"dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to 'Registro', new_user_registration_path, class:"dropdown-item" %></li>
                <% end %>
          </ul>
          </li>
        </ul>
    </div>
  </div>
</nav>